dist: trusty
sudo: true
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO_ENV="django>=1.11,<2.0" DB=sqlite
  - DJANGO_ENV="django>=1.11,<2.0" DB=postgres
  - DJANGO_ENV="django>=1.11,<2.0" DB=mysql
  - DJANGO_ENV="django>=2.0,<2.1" DB=sqlite
  - DJANGO_ENV="django>=2.0,<2.1" DB=postgres
  - DJANGO_ENV="django>=2.0,<2.1" DB=mysql

matrix:
  allow_failures:
    - python: "3.7-dev"
  exclude:
  - python: "2.7"
    env: DJANGO_ENV="django>=2.0,<2.1" DB=sqlite
  - python: "2.7"
    env: DJANGO_ENV="django>=2.0,<2.1" DB=postgres
  - python: "2.7"
    env: DJANGO_ENV="django>=2.0,<2.1" DB=mysql

install:
  - if [[ $DB == "mysql" ]]; then sudo apt-get install -qq libmysqlclient-dev && pip install mysqlclient; fi
  - if [[ $DB == "postgres" ]]; then pip install psycopg2; fi
  - pip install pip pipenv -U
  - pipenv install $DJANGO_ENV --skip-lock
  - pipenv install --dev --skip-lock
before_script:
  - mysql -u root -e 'create database machina_test;'
  - psql -c 'create database machina_test;' -U postgres
script:
  - make qa
  - make coverage
after_success:
  - codecov
branches:
  only:
    - master
